In [105]:
# Importing api requests
import requests
import json

# Importing Necessary Libraries for Predictive Modeling
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeRegressor

In [95]:
# Set my API Key
api_key = "OX9K2D1Q89P22TMN"

In [96]:
# Set base url for API
baseUrl = "https://www.alphavantage.co/query"
# Core Stock API Functions
def timeSeriesIntraday(symbol, interval):
    # Set base url for API
    baseUrl = "https://www.alphavantage.co/query"
    
    # Make API Request
    response = requests.get("https://www.alphavantage.co/query", params={
        "function": "TIME_SERIES_INTRADAY",
        "symbol": symbol,
        "interval": interval,
        "apikey": "OX9K2D1Q89P22TMN"
    })
    
    # Print Response
    print(response.text)
    
def timeSeriesIntradayExtendo(symbol, interval, yearMonth):
    # Set base url for API
    baseUrl = "https://www.alphavantage.co/query"
    
    # Make API Request
    response = requests.get("https://www.alphavantage.co/query", params={
        "function": "TIME_SERIES_INTRADAY_EXTENDED",
        "symbol": symbol,
        "interval": interval,
        "slice": yearMonth,
        "apikey": "OX9K2D1Q89P22TMN"
    })
    
    # Print Response
    print(response.text)

def timeSeriesDailyAdj(symbol):
    # Set base url for API
    baseUrl = "https://www.alphavantage.co/query"
    
    # Make API Request
    response = requests.get("https://www.alphavantage.co/query", params={
        "function": "TIME_SERIES_DAILY_ADJUSTED",
        "symbol": symbol,
        "apikey": "OX9K2D1Q89P22TMN"
    })
    
    # Print Response
    print(response.text)
    
def timeSeriesWeekly(symbol):
    # Set base url for API
    baseUrl = "https://www.alphavantage.co/query"
    
    # Make the API Request
    response = requests.get("https://www.alphavantage.co/query", params={
        "function": "TIME_SERIES_WEEKLY",
        "symbol": symbol,
        "apikey": "OX9K2D1Q89P22TMN"
    })

    # Print Response
    print(response.text)
    
def timeSeriesWeeklyAdj(symbol):
    # Set base url for API
    baseUrl = "https://www.alphavantage.co/query"
    
    # Make the API Request
    response = requests.get("https://www.alphavantage.co/query", params={
        "function": "TIME_SERIES_WEEKLY_ADJUSTED",
        "symbol": symbol,
        "datatype": "JSON",
        "apikey": "OX9K2D1Q89P22TMN"
    })

    # Print Response
    return(response.text)
    
def timeSeriesMonthly(symbol):
    # Set base url for API
    baseUrl = "https://www.alphavantage.co/query"
    
    # Make the API Request
    response = requests.get("https://www.alphavantage.co/query", params={
        "function": "TIME_SERIES_MONTHLY",
        "symbol": symbol,
        "apikey": "OX9K2D1Q89P22TMN"
    })

    # Print Response
    print(response.text)
    
def timeSeriesMonthlyAdj(symbol):
    # Set base url for API
    baseUrl = "https://www.alphavantage.co/query"
    
    # Make the API Request
    response = requests.get("https://www.alphavantage.co/query", params={
        "function": "TIME_SERIES_MONTHLY_ADJUSTED",
        "symbol": symbol,
        "apikey": "OX9K2D1Q89P22TMN"
    })

    # Print Response
    print(response.text)

In [97]:
# Testing functions
# timeSeriesIntraday("AAPL", "60min")
# timeSeriesIntradayExtendo("AAPL", "60min", "year1month1")
#timeSeriesDailyAdj("RIOT")
#timeSeriesWeekly("IBM")
# timeSeriesWeeklyAdj("COIN")
#timeSeriesMonthly("AMD")
#timeSeriesMonthlyAdj("CAT")

In [98]:
# Preparing Data
# Weekly Data Taken From Alpha Vantage API
# Problem: Predicting future price of a stock based on its historical data
jsonFile = timeSeriesWeeklyAdj("COIN")

In [99]:
#Creating a Pandas DF and Cleaning the Data

data = json.loads(jsonFile)
data = data['Weekly Adjusted Time Series']
index = []
columns=[]
for key in data:
    index.append(key)
#print(index)
values = list(data.values())
#print(values)
innerDict = values[0]
for key in innerDict:
    columns.append(key)
#print(columns)
#print(data)
df = pd.DataFrame(values, columns=columns, index=index)
df['1. open'] = df['1. open'].astype(float)
df['2. high'] = df['2. high'].astype(float)
df['3. low'] = df['3. low'].astype(float)
df['4. close'] = df['4. close'].astype(float)
df['5. adjusted close'] = df['5. adjusted close'].astype(float)
df['6. volume'] = df['6. volume'].astype(float)
df['7. dividend amount'] = df['7. dividend amount'].astype(float)
df.head()

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount
2022-12-14,39.980,46.33,38.50,40.19,40.19,46482904.0,0.0
2022-12-09,47.980,49.85,40.15,40.24,40.24,53601053.0,0.0
2022-12-02,43.300,47.70,41.51,47.67,47.67,57123348.0,0.0
2022-11-25,43.600,46.17,40.61,44.28,44.28,64282378.0,0.0
2022-11-18,55.695,58.00,44.31,45.26,45.26,93272794.0,0.0

In [100]:
# Perform feature engineering to create new features that may be useful for prediction

df["avg_price"] = (df["2. high"] + df["3. low"]) / 2
df.head()

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,avg_price
2022-12-14,39.980,46.33,38.50,40.19,40.19,46482904.0,0.0,42.415
2022-12-09,47.980,49.85,40.15,40.24,40.24,53601053.0,0.0,45.000
2022-12-02,43.300,47.70,41.51,47.67,47.67,57123348.0,0.0,44.605
2022-11-25,43.600,46.17,40.61,44.28,44.28,64282378.0,0.0,43.390
2022-11-18,55.695,58.00,44.31,45.26,45.26,93272794.0,0.0,51.155

In [110]:
# Select a model: use linear regression
model = LinearRegression()

# Split the data into training and test sets
X = df[["avg_price"]]
y = df["4. close"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train the model on the training data
model.fit(X_train, y_train)

# Evaluate the model on the test data
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 88.76359888490241

In [104]:
# Use the trained model to make predictions on new data
new_data = pd.DataFrame({"avg_price": [100, 150, 200]})
predictions = model.predict(new_data)
print("Predictions:", predictions)

Predictions: [ 97.6344386  147.22953877 196.82463894]

In [107]:
model = DecisionTreeRegressor()

X = df[["avg_price"]]
y = df["4. close"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train the model on the training data
model.fit(X_train, y_train)

# Evaluate the model on the test data
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 243.23421111111116

In [108]:
# Use the trained model to make predictions on new data
new_data = pd.DataFrame({"avg_price": [100, 150, 200]})
predictions = model.predict(new_data)
print("Predictions:", predictions)

Predictions: [ 90.49 131.52 189.16]